# Generated by Django 3.2.13 on 2022-10-17 08:17

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20221017_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
