# Generated by Django 3.2.13 on 2022-10-17 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20221017_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Thumbnail',
            new_name='thumbnail',
        ),
    ]
