# Generated by Django 3.2.13 on 2022-10-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='running_time',
            field=models.TextField(),
        ),
    ]
