# Generated by Django 3.2.13 on 2022-10-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_running_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='running_time',
            field=models.IntegerField(),
        ),
    ]
